# Generated by Django 4.2.4 on 2023-08-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='bibekrai655@gmail.com', max_length=30),
            preserve_default=False,
        ),
    ]
